services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: fitness_club
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - '3306:3306'
    volumes:
      - fitness-club:/var/lib/mysql
volumes:
  fitness-club: